# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
cray-service:
  # imagesHost: "s-lmo-anastl:5000"
  nameOverride: nnf-ec
  type: DaemonSet
  service:
    enabled: False
  replicaCount: 1
  serviceAccountName: nnf-ec
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "storage"
      effect: "NoSchedule"
  containers:
    cray-nnf-ec:
      name: cray-nnf-ec
      image:
        repository: cray/cray-nnf-ec
        tag: latest
        pullPolicy: Never
      command: ["nnf-ec"]
      args: ["--http", "--port=8080", "--mock", "--log", "--verbose"]
      ports:
        - name: nnf-api-service
          containerPort: 8080
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /dev
          name: dev-dir
        - mountPath: /mnt
          name: mnt-dir
          mountPropagation: Bidirectional
  volumes:
    - name: dev-dir
      hostPath:
        path: /dev
    - name: mnt-dir
      hostPath:
        path: /mnt
  nodeSelector:
    cray.dpm.dg.dpm-nnf-node: "true"

global:
  chart:
    name: "" # set at deploy time automatically, no need to ever set explicitly
    version: "" # set at deploy time automatically, no need to ever set explicitly
